# Generated by Django 5.0.4 on 2024-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
    ]
