# Generated by Django 5.0.4 on 2024-05-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0003_menuitem_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menu', to='footwearapp.menumodal'),
        ),
        migrations.AddField(
            model_name='menumodal',
            name='badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menumodal',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menumodal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
