# Generated by Django 5.0.4 on 2024-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0004_alter_submenu_menu_item_menumodal_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('badge', models.CharField(max_length=100)),
            ],
        ),
    ]
