# Generated by Django 5.0.4 on 2024-05-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0008_category_product_delete_breadcrumbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
