# Generated by Django 5.0.4 on 2024-05-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0009_remove_product_category_remove_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
