# Generated by Django 5.0.4 on 2024-05-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0014_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
