# Generated by Django 5.0.4 on 2024-05-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0017_menimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menimage',
            name='name',
            field=models.CharField(default='default_value_here', max_length=50),
        ),
    ]
