# Generated by Django 5.0.4 on 2024-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0018_menimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menimage',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menimage',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
