# Generated by Django 5.0.4 on 2024-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0019_menimage_text_alter_menimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menimage',
            name='text',
            field=models.TextField(default='', max_length=10),
        ),
    ]
