# Generated by Django 5.0.4 on 2024-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0021_alter_menimage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='WomenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='womenimage/')),
            ],
        ),
    ]
