# Generated by Django 5.0.4 on 2024-05-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0025_getintouch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menimage',
            name='text',
            field=models.TextField(default='', max_length=255),
        ),
    ]
