# Generated by Django 5.0.4 on 2024-05-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0026_alter_menimage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menimage',
            name='text',
        ),
    ]
