# Generated by Django 5.0.4 on 2024-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0028_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='num_reviews',
        ),
    ]
