# Generated by Django 5.0.4 on 2024-07-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0033_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
