# Generated by Django 5.0.4 on 2024-07-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0035_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menimage',
            name='name',
        ),
    ]
