# Generated by Django 5.0.4 on 2024-07-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0036_remove_menimage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewAllProduct',
        ),
    ]
