# Generated by Django 5.0.4 on 2024-07-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0037_delete_viewallproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WomenImage',
        ),
    ]
