# Generated by Django 5.0.4 on 2024-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0038_delete_womenimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='review/')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
