# Generated by Django 5.0.4 on 2024-07-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0039_productreview_delete_productdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddImage',
        ),
        migrations.DeleteModel(
            name='GetInTouch',
        ),
        migrations.DeleteModel(
            name='Sellerimage',
        ),
    ]
