# Generated by Django 5.0.4 on 2024-07-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footwearapp', '0041_addimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddImage',
        ),
    ]
